# Generated by Django 4.2.9 on 2024-01-21 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apostilas', '0002_viewapostila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='arquivo',
            field=models.FileField(upload_to='media/apostilas'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
