# Generated by Django 5.1.4 on 2024-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='pergunta',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='resposta',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
